data_params: {
    model_config: {
        name: "GaussianLoDModel",
        kwargs: {
            fork: 2,
            gs_attr: "2D",
            color_attr: "RGB",
            feat_dim: 32,
            view_dim: 3,
            appearance_dim: 0,
            n_offsets: 10, 
            voxel_size: 0.001,
            render_mode: "RGB+ED",
        }
    },
    source_path: "data/fusion/train", 
    pp_opt_yaml_path: "config/base/small_scene",  
    dataset_name: "matrix_city_fusion",
    scene_name: "aerial_street_fusion",
    images: "images",
    resolution: -1,
    white_background: False,
    random_background: False,
    resolution_scales: [1.0],
    data_device: "cuda",
    eval: False,
    ratio: 1,
    data_format: "colmap",
    llffhold: 8,           # <--- 【新增这一行】通常用于定义测试集的划分比例（例如 8 表示每 8 张取 1 张作为测试集） 不过eval:false会使这行失效
    add_mask: False,
    add_depth: False,
    add_aerial: True,
    add_street: True,
    aerial_lod: "multi",
    street_lod: "multi",
    dist_ratio: 0.999,
    partition: False,
    scale: 1.0,
    center: [0,0,0]
}